### PR TITLE
Implement reaction handling as part of OBMol

### PR DESCRIPTION
**Pull request by baoilleach**
As described at https://github.com/openbabel/enhancement-proposals/blob/master/reactions-as-obmols/reaction-handling.md.

I still have some reaction formats left but I'd like to get in a PR now, and get some feedback, as all the tests pass, and the rest will be a bit of a slog.

SMILES, RINCHI and RXN all support reactions via OBMols now. I've added an OBReactionFacade class to simplify things. In short, reactions are supported via three attributes, a flag on an OBMol, and two OBPairInteger data objects on an OBAtom, "rxncomp" and "rxnrole".

### CODE REVIEW

**Comment by baoilleach** [comment]
I see there's a minor conflict. But apart from that, any thoughts on this?

**Comment by ghutchis** [comment]
Good to merge. Sorry - should have pushed me sooner. :+1

**Comment by ghutchis** [comment]
Do you want to squash this branch or keep the commit history?

**Comment by baoilleach** [comment]
Keep? I have no strong feelings, but if I ever have to look at a diff for this, I'd prefer to be looking at the individual commits.

**Pull request merged**
