### PR TITLE
Gaussformat reading multiple charge modles 2

### PR DESCRIPTION
**Pull request by mmghahremanpour**
SetOrigin() is added.

### CODE REVIEW

**Comment by mmghahremanpour** [comment]
please let me know if I still need to modify this patch!

**Comment by ghutchis** [comment]
Thanks for the reminder - sorry for the very slow review.

It looks okay. My last concern is that with the current implementation, there's nothing guaranteeing that a molecule will have a full set of partial charges.

I think I'd prefer that the OBPartialCharge class only accept charges as a full vector<double> and checks to make sure it's equal to the number of atoms before storing.

The reader should then push_back() into a temporary vector in the gauss format.cpp code.

This way, if there's somehow a corrupted file (e.g., it got killed by the queuing software before the job finished) the partial charges are still safe - it won't store a set of ESP charges that are only half the molecule.

I realize that's an unlikely case, but I'm trying to think from the library API perspective - you can access a set of vector<double> but set the charges one-by-one. That's asymmetric.

**Comment by mmghahremanpour** [comment]
The code has been updated based on your suggestions.

**Comment by ghutchis** [comment]
Thanks - sorry for the long review process on this one.

**Comment by mmghahremanpour** [comment]
Thank you for merging. 
Would you please review #1753 as well? It is also related to reading Gaussian log files. 

Thank you,

Mohammad

**Pull request merged**
