### PR TITLE
Compile position independent code for shared libraries.

### PR DESCRIPTION
**Pull request by susilehtola**
This PR adds the missing CMake rule about position independent object files, which are necessary to be able to compile shared libraries, see issue #1574 .

### CODE REVIEW

**Comment by baoilleach** [comment]
I'd be okay with this as an option, but I'd like to get to the bottom of what's happening with #1574 first.

**Comment by baoilleach** [comment]
Can you change this to a option for non-Windows builds and default it to true?

**Comment by baoilleach** [comment]
On second thoughts, let's just merge it for now, and see whether it causes any problems. Any problems with this @ghutchis ?

**Comment by ghutchis** [comment]
I'm fine with merging.

**Comment by cowsandmilk** [comment]
The thing that confuses me is that [cmake sets this to be true](https://cmake.org/cmake/help/v3.0/prop_tgt/POSITION_INDEPENDENT_CODE.html) when build_type is SHARED , which it is here.

This is why [Fedora's build logs](https://kojipkgs.fedoraproject.org//packages/openbabel/2.4.1/5.fc26/data/logs/x86_64/build.log) already have -fPIC and work fine. And builds on my ubuntu system use -fPIC and work fine.

**Comment by ghutchis** [comment]
Agreed 110% - it should be fine. But I don't see the harm in turning on -fPIC if there's an issue with CMake. I see this patch as a workaround, since there's clearly an issue.

**Comment by baoilleach** [comment]
It's the static inclusion of external libraries into the gui executable that's the problem (I think?), not so much shared library build. The variable names in the CMake file are a bit confused.

**Pull request merged**
