### PR TITLE
New plugin for generating VDW surface points

### PR DESCRIPTION
**Pull request by mj-harvey**
Hi,

This plugin, "pointcloud" generates points on the vdw surfaces around a molecule
 Radius multipliers and point densities can be specified
 Output is in (pseudo) xyz format

### CODE REVIEW

**Comment by ghutchis** [comment]
Looks nice, although I have some questions beyond point clouds.. Many people would like solvent-accessible or solvent-excluded surfaces at variable probe radii. The "radius multiplier" seems like it would be more useful from a user perspective as an additive factor (e.g., VdW + 0, +1 + 1.5Ang, etc.)

**Comment by ghutchis** [comment]
Oh, I also forgot to mention that while point clouds are nice, exporting to something like STL (i.e., taking the points and triangulating) would be really highly appreciated.

**Comment by mj-harvey** [comment]
I can add a probe radius too, no problem.

**Comment by mj-harvey** [comment]
I appreciate that would be useful, but it goes beyond our use case. I'm not
sure how to do either the triangulation or write STL, so it will probably
require more resource than I can spare right now. I'll put it on the Todo
list though.

Matt

**Comment by ghutchis** [comment]
The probe radius would be great. No worries about STL / triangulation. I suspect I can coerce an undergrad to work on that this summer.

Two spaces, no tab:
(setq-default indent-tabs-mode nil)
(setq c-basic-offset 2)
(setq default-tab-width 2)

Thanks!

**Comment by mj-harvey** [comment]
closed to resubmit again

**Pull request closed without merging**
