### PR TITLE
Fixed compiler warnings in libinchi.

### PR DESCRIPTION
**Pull request by dspoel**
We should try to get rid of all compiler warning such that we can require this of all new code as well.
% grep -c warning make.log 
85
It does seem doable.

### CODE REVIEW

**Comment by baoilleach** [comment]
Modifications to inchi should be made upstream. Also there is a new version available, probably with new warnings. I note that the new version has a clause saying that modifications are not allowed :-/

**Comment by baoilleach** [comment]
But for sure we should get rid of warnings.

**Comment by dspoel** [comment]
Interesting. Then do we need to include it? Could we have an external library only?

**Comment by ghutchis** [comment]
If you happen to have libinchi installed, you can compile with OPENBABEL_USE_SYSTEM_INCHI 

While I'd be okay with changing compiler flags for the inchi directory (e.g. adding CFLAGS='-w'), I'd really rather have an unmodified inchi. It's not our code.

(I'll note that sending patches to eliminate obvious warnings haven't gone anywhere, sadly.)

**Comment by dspoel** [comment]
Closing this.

**Pull request closed without merging**
