### PR TITLE
Fix output format in the cifformat writer

### PR DESCRIPTION
**Pull request by afonari**
Related to https://github.com/openbabel/openbabel/issues/2160.

### CODE REVIEW

**Comment by baoilleach** [comment]
Can you add the file the OP provided as a test case to prevent future regressions?

**Comment by afonari** [comment]
Add a unit test. For my education, can you tell me how to run a certain unit test (for example test_pdbreadfile_4) and all of them using `make test`.

**Comment by ghutchis** [comment]
@afonari you can run `ctest -V -R pdbread` the -R will match tests with specified regex.

**Comment by baoilleach** [comment]
Alternatively the following describes how to run a specific test directly.
Especially useful if you are using a debugger:
https://open-babel.readthedocs.io/en/latest/Contributing/Testing.html#running-tests

**Pull request merged**
