### PR TITLE
In the Python bindings, reset the DL open flags after importing _openbabel

### LINKED ISSUE #917: Use of DL flags in Python bindings can cause problems
A bug was reported for scipy at http://projects.scipy.org/numpy/ticket/1148

"""Openbabel Python bindings call
   sys.setdlopenflags(sys.getdlopenflags() | dl.RTLD_GLOBAL)

Obviously, this *will* causes problems down the stream, as symbols of subsequently loaded libraries are no longer isolated...

You can also reproduce the crash without Openbabel,
   python -c 'import sys, dl; sys.setdlopenflags(sys.getdlopenflags() | dl.RTLD_GLOBAL); import foo'

This behavior of Openbabel's is highly suspect IMHO. If it needs to enable this flag, it probably ought to also restore its value after loading whatever needs loading. """

Maybe it's possible to set this flag back to the default after loading various plugins??

Reported by: @baoilleach

### PR DESCRIPTION
**Pull request by baoilleach**
Should have fixed this a long time ago. The DL flags kludge was needed for some platforms or else the plugins didn't load. I can't say whether it's still needed but at least now the code resets the flag value after forcing the plugins to load with OBPlugin::LoadAllPlugins().

I believe this fixes #917, #1222, and #1702. I can't reproduce the original problems though.

### CODE REVIEW

**Comment by baoilleach** [comment]
I was pulling my hair out over this failure, which occurred only with the Clang build (on Linux)...but it's right. It's not loading the plugins that requires this to be set, but "import _openbabel" (or it's equivalent) in the openbabel.py. That pulls in the .so file. Still don't understand the underlying reason why, but at least I know where the fix goes now.

**Comment by ghutchis** [comment]
Looks *great*

**Comment by mwojcikowski** [comment]
Yay, no more conflicts with Scipy, etc (basically any fortran code run with f2py). 

I believe it also fixes numpy/numpy#1746

**Comment by baoilleach** [comment]
I keep thinking about this and the difference between the clang and gcc builds. It's nothing to do with the compiler, so it must be something about the linker flags when either the plugins or openbabel.so are being created. I think that is where the real fix should be.

**Pull request merged**
