### PR TITLE
Swig fix for python package

### PR DESCRIPTION
**Pull request by mcs07**
This commit updates `scripts/python/openbabel-python.i` to match recent fixes to `scripts/openbabel-python.i`. It also bumps the version number in `scripts/python/setup.py` to prepare for uploading the fixes to PyPI to fix installing the python bindings through `pip install openbabel`.

### CODE REVIEW

**Comment by baoilleach** [comment]
Um....remind me why we needed two openbabel-python.i files?

**Comment by mcs07** [comment]
OK I just looked back in the history, and I think the intention was to add `scripts/python/openbabel-python.i` as a symbolic link to the pre-existing `scripts/openbabel-python.i`. This was because package that is submitted to PyPI is created from the contents of the `python` directory. See here: https://github.com/openbabel/openbabel/commit/3cf839f34eb3375f2cebc57193705b8f1192e676

However, it doesn't look like this has worked correctly, and we now have two `openbabel-python.i` files that are out of sync...

It's probably best to figure out a way to go back to having just a single file, but still maintaining the ability to build the python bindings package for submission to PyPI. It may be possible to update `MANIFEST.in` to pull in the file from the parent directory, or if not, maybe we should just keep `scripts/python/openbabel-python.i`, however, that will be inconsistent with the other language bindings.

**Comment by mcs07** [comment]
Hmmm, looks like it was this commit https://github.com/openbabel/openbabel/commit/81caf8f8fd1cb45018f5d84dff100869d3f6e44b that changed it from a symbolic link to a second copy of the file. Not sure what the motivation was.

**Comment by baoilleach** [comment]
I agree - if one file and no symlinks are possible, that would be simplest.

**Pull request closed without merging**
