### PR TITLE
[MRG] Support Python 2.x Unicode

### PR DESCRIPTION
**Pull request by mwojcikowski**
Fix for #325

### CODE REVIEW

**Comment by mwojcikowski** [comment]
The solution is much simpler than I've anticipated. There is `SWIG_PYTHON_2_UNICODE` variable that has to be defined to [support unicode in Python 2.x](http://www.swig.org/Doc3.0/Python.html). Although swig has to be at least 3.0.8 to work, which is the case for Anaconda - we should be fine. There shouldn't be any downside to this resolution for earlier versions.

**Comment by mwojcikowski** [comment]
I've tested it on Anaconda build and it truly fix #325

**Comment by baoilleach** [comment]
Can you confirm for sure that it doesn't cause a problem with earlier swigs?

**Comment by mwojcikowski** [comment]
Travis use Swig 2.0.x ([log](https://travis-ci.org/openbabel/openbabel/jobs/145775600#L254)) and all tests pass. Defining arbitrary variable should not mess with anything (unless it is not meant for anything else). I may try building OB with Swig 3.0.7 which is just before that feature was used if you think it will help.

**Comment by baoilleach** [comment]
Good point about Travis. Doh!

**Pull request merged**
