### PR TITLE
Fix memory leak in InChi handling

### PR DESCRIPTION
**Pull request by romanbsd**

### CODE REVIEW

**Review by baoilleach — APPROVED** [review]
Nice!

**Comment by romanbsd** [comment]
I've got another 5 PRs pending :)

**Comment by tyler92** [comment]
@baoilleach @ghutchis Hi. Can we merge this PR and probably other @romanbsd's PRs? I'm going to send several patches that fix crashes/ASAN warning and maybe it's better to merge already open PRs to avoid conflicts or double work

**Comment by ghutchis** [comment]
@tyler92 - I've been too busy to spend much time on OB maintenance unfortunately. OTOH it's definitely time for a 3.2 release, so I'll set aside some time over the next few weeks.

**Pull request merged**
