### PR TITLE
avoid non-finite bond vectors

### PR DESCRIPTION
**Pull request by dkoes**
This is putting lipstick on a pig.  The real issue is hydrogens being added where they have no business (#1925).  When placing a new hydrogen, the GetNewBondVector code assumes a hybridization of 2-6.  Otherwise it returns an infinite vector which gets turned into an atom at the origin resulting in a crazy structure.  This "fix" ensures the returned bond vector isn't horrible if the hybridization state is weird.

An example file is attached.
`babel -isdf 3o8g_uff.sdf -omol2 test2_addH_uff.mol2 -h`

[3o8g_uff.sdf.gz](https://github.com/openbabel/openbabel/files/3143788/3o8g_uff.sdf.gz)

### CODE REVIEW

**Comment by ghutchis** [comment]
While I agree there's a deeper underlying problem, this isn't lipstick either - it's basic defensive programming.

I'd love to turn the test file into an actual unit test (e.g., checking if there's an atom v. close to the origin).

@baoilleach and I agree that we'd like all PR to include regression tests and this seems like an important one.

**Comment by dkoes** [comment]
The reason I didn’t bother with a test is because the result still isn’t right (those hydrogens shouldn’t be added).

**Comment by ghutchis** [comment]
I mean, I think we should still add a unit test for "no, there is not a hydrogen at the origin".

Let's take the hydrogens as a separate issue / pull request.

@baoilleach - there's a weird valence issue with this file -- the azide is getting a hydrogen in the middle and at the end. I suspect the problem is that the SDF is mal-formed (i.e., even ChemDraw puts an "h" on the terminal N). However, =N= should never be protonated.

**Comment by baoilleach** [comment]
I will look at it asap. Where's the original from @dkoes?

**Comment by dkoes** [comment]
It's the ligand in the PDB 3O8G: https://www.rcsb.org/pdb/download/downloadLigandFiles.do?ligandIdList=O8G&structIdList=3O8G&instanceType=all&excludeUnobserved=false&includeHydrogens=false

**Comment by baoilleach** [comment]
Open Babel reads this SDF file just like Biovia Draw (I just tested with 2019 version). That is, there is an implicit hydrogen on the central nitrogen. In the other words, the error is in the original file - we read it correctly. 

Again, where did this file come from? The link you provided has an SDF file with "M  CHG  2  21   1  22  -1", which would have given the correct number of hydrogens. The file at the top of the bug report is missing this.

**Comment by francoep** [comment]
That file was created by downloading the file that david linked to, and pushing it through the UFF forcefield in rdkit:
`mol=AllChem.MolFromMolFile(pdbligfile)`
`AllChem.UFFOptimizeMolecule(mol)`

which was then written out to the file attached. The link we provided is the database where the SDF exists. It's a SDF file for a ligand that was deposited in the PDB. Note: that line is present in the original downloaded file, but is then absent after running through rdkit.

**Comment by baoilleach** [comment]
Thanks @francoep. I'm pretty sure that RDKit can roundtrip charges so there's something funny going on there - you might want to report it over at https://github.com/rdkit/rdkit/issues if you can verify that it's an RDKit issue.

**Comment by dkoes** [comment]
This is basic defensive programming - what is needed to get it merged?

**Comment by baoilleach** [comment]
Reading through, @ghutchis asked for a test.

**Comment by ghutchis** [comment]
Yeah, I understand it's not the root cause, but having fixed umpteen of these kinds of bugs, I'd really, *really* appreciate having a new unit test of some sort to make sure this lipstick doesn't come back.

**Comment by dkoes** [comment]
There's a test now... still don't like what hydrogens are added, but they at least don't have crazy bond lengths.

**Comment by ghutchis** [comment]
Much appreciated.

**Pull request merged**
