### PR TITLE
Fix#1768: Segfault upon reading GAMESS outputs of DFTB3 calculations

### PR DESCRIPTION
**Pull request by serval2412**
See https://github.com/openbabel/openbabel/issues/1768#issuecomment-374051555
for bt and some explanations

### CODE REVIEW

**Comment by baoilleach** [comment]
Thanks. Would you consider including a test case? Our test suite is run automatically and will let us know if a future commit would break your code.

**Comment by serval2412** [comment]
I understand but it's another step to do and I don't want to dive in this part.
Don't hesitate to refuse and close the patch if you think it can't be accepted with a test case.

**Comment by baoilleach** [comment]
It can be accepted but it'll just slow down the review, because I'll have to actually look and see what you've done. With a test case, I can just go "fine". :-)

**Comment by serval2412** [comment]
About the test case, you can check the attachment of #1768. Without the patch it indeed segfaults, with it it's ok. Now I recognize that it may not be the right fix (perhaps I'm just hidding the pb).
Also, I checked the existing test cases but I didn't found something enough similar to copy cat it.

**Comment by ghutchis** [comment]
Looks fine for now - it does fix the crash with the #1798 1768.

**Comment by baoilleach** [comment]
Regarding a testcase, something in testbindings.py like (note: untested):
'''
def test1768:
   mol = pybel.readstring("gamout", os.path.join(testfiles, "testfile.gamout.gz")).OBMol
   self.assertEqual(22, mol.NumAtoms())
''''
or if you prefer C++, a similar test in regressions.cpp.

**Comment by serval2412** [comment]
baoilleach: even if I understand the interest of testcases, I'm not very interested in creating some. Fixing a bug is far more motivating.

**Pull request merged**
