### PR TITLE
VASP Write. "w" and "z" options.

### PR DESCRIPTION
**Pull request by orex**
https://github.com/openbabel/openbabel/pull/188

### CODE REVIEW

**Comment by baoilleach** [comment]
Looks good. Thanks.

**Comment by orex** [comment]
I also want to submit a test case for this, but the problem is, that I don't know the appropriate way to get a temporary folder files store within the test.

**Comment by baoilleach** [comment]
If you can, it's best to avoid this problem by writing to a string instead of disk. You can just imagine people running the tests with "sudo" and creating all sorts of permissions problems. Could you describe the problem exactly - maybe I can help...?

**Comment by orex** [comment]
The stream store is not working for VASP, because the information about structure spread over many files.

**Comment by baoilleach** [comment]
Ah, I see. You may need to add a special option that writes everything to one file for testing purposes.

**Pull request merged**
