### PR TITLE
Fix PDB writer to obey space group naming convention for rhombohedral groups (fixes #251)

### LINKED ISSUE #251: PDB writer is not obeying space group naming convention for rhombohedral groups
In particular (from http://deposit.rcsb.org/adit/docs/pdb_atom_format.html ):
**For a rhombohedral space group in the hexagonal setting, the lattice type symbol used is H.**

For example this:
`_symmetry_space_group_name_H-M   'R -3 m :H'`

Should be converted to:
`H-3m`

The code to fix is around: https://github.com/openbabel/openbabel/blob/master/src/formats/pdbformat.cpp#L557

Similar patch exists for the Computational Crystallography Toolbox: http://sourceforge.net/p/cctbx/mailman/message/19334798/

### PR DESCRIPTION
**Pull request by alexandr-fonari**
fixes #251 
Reference CIF is available from COD: http://www.crystallography.net/cod/cif/9/01/53/9015328.cif
http://www.crystallography.net/cod/9015328.html

### CODE REVIEW

**Comment by alexandr-fonari** [comment]
I will test a little bit more, will update here once I'm sure it works.

**Comment by ghutchis** [comment]
Out of curiosity, does it seem as if the reader correctly reads the space groups?

**Comment by alexandr-fonari** [comment]
Will check that.

**Comment by alexandr-fonari** [comment]
Ok, check this out. Let me know.
I tested using:

```
./bin/babel 9015328.cif test.pdb
./bin/babel test.pdb test1.cif
./bin/babel 9015328.cif test2.cif
diff test1.cif test2.cif 
3c3
< _chemical_name_common 'test.pdb'
---
> _chemical_name_common 'Wassonite'
57,60c57,60
<     Ti0     Ti   0.00000   0.00000   0.50002   1.000
<     Ti1     Ti   0.00000   0.00000   0.37800   1.000
<     S2      S    0.00000   0.00000   0.00000   1.000
<     S3      S    0.00000   0.00000   0.22601   1.000
---
>     Ti1     Ti   0.00000   0.00000   0.50000   1.000
>     Ti2     Ti   0.00000   0.00000   0.37800   1.000
>     S1      S    0.00000   0.00000   0.00000   1.000
>     S2      S    0.00000   0.00000   0.22600   1.000
```

**Comment by alexandr-fonari** [comment]
If someone could give me a hand fixing VS build, that would be great! The crux of the issue (I think) is making RemoveWhiteSpaceUnderscore _public_ from openbabel/math/spacegroup.h.

**Comment by alexandr-fonari** [comment]
If anyone could review it, that would be great!

**Comment by ghutchis** [comment]
I hadn't realized you updated the pull - but you can't remove calls from headers. That breaks API, even if no one is using it. Find another solution.

**Comment by alexandr-fonari** [comment]
What do you mean by 'remove calls from headers'?

All I did is added two 'internal' functions into pdbformat. Am I missing something?

**Comment by ghutchis** [comment]
You've removed the declaration in spacegroup.h

https://github.com/alexandr-fonari/openbabel/commit/16b0826fa94389a01ed2a0db263cb011452f0810

**Comment by alexandr-fonari** [comment]
That was an intermediate change. It is not present in the final set of changes: https://github.com/openbabel/openbabel/pull/252/files

**Comment by ghutchis** [comment]
Manually merged (to squash commits). Resolves #251 #252.

**Comment by alexandr-fonari** [comment]
Thank you for merging. Sorry for the confusion with several commits.

Alexandr.

**Pull request closed without merging**
