### PR TITLE
Add svg balls and sticks depiction

### PR DESCRIPTION
**Pull request by jnavila**
This format is named svgbs, but this is really a svg file.

This PR is for test and review. It has only been tested with the dioxin file.

Up to now there are some known limitations:
 * How to handle wobbly bonds and ring bonds (I don't have any clue what this means)
 * The conversion of a file containing more than one molecule will fail (not tested). It brings more complexity, because that would imply keeping the svg definitions and saving everything in a memstream until the very end. That would spill svg related code.
 *  The tool does not allow two filters to have the same name. But the name is used as the file extension. Thus, we can not use svg for this new format.

This is a proposed fix for  #193

### CODE REVIEW

**Comment by fredrikw** [comment]
I would prefer to have this as an option to the svgformat (that eventually could be ported to pngformat later on) it that is possible

**Comment by ghutchis** [comment]
@fredrikw No worries, when I merge it, it will end up in svgformat as an option. That part isn't critical towards the feature request and bounty. I'll check it out shortly.

**Comment by jnavila** [comment]
In fact, this patch completely breaks any output for multiple molecules.

I'm planning to fix point 2 an 3 by making this an option, and reworking the seperation of roles between svgformat and depictor/svgpainter. 

More input files for test are needed. The quinin mol2 file provided at http://pqr.pitt.edu/ can not be read. Where can I find files containing more than one molecule?

**Comment by ghutchis** [comment]
First off, there's an error in svgpainter:
diff --git a/src/depict/svgpainter.cpp b/src/depict/svgpainter.cpp
index 7d9bbd7..43311c7 100644
--- a/src/depict/svgpainter.cpp
+++ b/src/depict/svgpainter.cpp
@@ -191,7 +191,7 @@ namespace OpenBabel
         m_ofs << "<radialGradient id='radial";
         m_ofs << RGBcode(it->first)<< RGBcode(it->second) << "' ";
         m_ofs << "cx='50%' cy='50%' r='50%' fx='30%' fy='30%'>\n";
-        m_ofs << "  <stop offset=' 0%' start-color=" << MakeRGB(it->first) << "
+        m_ofs << "  <stop offset=' 0%' stop-color=" << MakeRGB(it->first) << " 
         m_ofs << "  <stop offset='100%' stop-color=" << MakeRGB(it->second) << 
         m_ofs << "</radialGradient>\n";
       }

**Comment by ghutchis** [comment]
Er, it should be "stop-color" not "start-color"
+        m_ofs << "  <stop offset=' 0%' stop-color=" << MakeRGB(it->first) << "

**Comment by ghutchis** [comment]
Here's a multi-molecule file:
https://www.dropbox.com/s/8bsj38hyps3o6jy/AA.sdf.gz?dl=0

Here's a .tar.gz with a bunch of files:
https://www.dropbox.com/s/0fikn6834dc0h9h/AA.tar.gz?dl=0

**Comment by ghutchis** [comment]
I'm not actually sure what a "wobbly bond" is. Don't worry about ring bonds, they look just fine.

It might be nice to add support for aromatic bonds (i.e., if a bond is aromatic, you draw a second line like a double bond, but it's dashed, e.g. http://www.mdpi.com/molecules/molecules-19-07008/article_deploy/html/images/molecules-19-07008-g013-1024.png

**Comment by jnavila** [comment]
Oops. Sorry for the error... I was already on the next stage.

**Comment by ghutchis** [comment]
No sweat. It looks great and I think you're very close to finishing this off. Thanks!

**Comment by ghutchis** [comment]
Do you intend to merge with the SVG format, or do you consider this finished? Thanks.

**Comment by jnavila** [comment]
Sorry for not giving news. I expected to spend another evening to refine things, but did not manage. Do you have a time frame for this feature?

Speaking of the merge with the SVG format, which option would you choose for switching to this version?

**Comment by jnavila** [comment]
Can we join a chat room somewhere?

**Comment by ghutchis** [comment]
Sorry, I've been busy.. We can probably find a time/channel on IRC on Monday or Tuesday? Maybe #openbabel ?

**Comment by jnavila** [comment]
I had some issues running on multiple molecules, even on master. But cutting the tail of the file seems to make the trick.

**Comment by jnavila** [comment]
Well, the PR is in a state where it feels quite safe. I would prefer to rebase it in another branch and clean up the fixup commits. I added a -xS option to output to ball&stick, and the aromatic rendering.

Please feel free to comment.

**Comment by jnavila** [comment]
Is this OK?

**Comment by ghutchis** [comment]
Yes, looks great. Please feel free to rebase and re-submit. I think this is a great new feature, thanks!

**Pull request closed without merging**
