### PR TITLE
Fix #2428 Molecular data in png

### LINKED ISSUE #2428: broken inclusion of model in .png files as string
- [X] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version:  3.1.1
Operating system and version:  Linux Debian 12/bookworm [testing], Python 3.9.8

## Expected Behavior

According to `obabel -L png`, it is possible to append/include e.g., the mol file to/in the `.png` written. See e.g., legacy  documentation of OpenBabel 2.3.1 [here](http://openbabel.org/docs/current/FileFormats/PNG2_format.html) and comment by @frederikw in issue report [here](https://github.com/openbabel/openbabel/issues/2426).

## Actual Behavior

Observation: The `.png` are written and are intelligible.  By report of the CLI, the inclusion of the structure file however fails.

Suggested changes, 1st class:
+ Bug fix to restore the functionality.
+ Addition of an explicit entry in the current version of the program documentation.

Suggested changes, 2nd class:
+ With the `.pngj` format ([documentation](http://wiki.jmol.org/index.php/File_formats/Export)), Jmol apparently offers a similar export of static (classical `.png` like) and interactive (model) data.  In Jmol, it is possible, e.g., to read this extended `.png`, to interact and export the model as `.sdf` «as usual».  See archive  pngj_examples.zip for examples.  It would be nice if Jmol's `.pngj` would be understood by OpenBabel, and the augmented `.png` written by OpenBabel could be read by Jmol as in «accessing the model data».

## Steps to Reproduce

```bash
$ obabel -:"CC(=O)Cl" -O mymol.png -xO smi
==============================
*** Open Babel Error  in PNG Format
  Not a PNG file
==============================
*** Open Babel Error  in PNG Format
  Failed to embed molecule(s)
1 molecule converted
```
The image is written and intelligible.  The subsequent attempt to recover the SMILES string from the `.png` however fails, and file `smiles.txt` stays empty.

```bash
$ obabel mymol.png -osmi -O smiles.txt
==============================
*** Open Babel Error  in PNG Format
  Not a PNG file
1 molecule converted
```

[example_pngj.zip](https://github.com/openbabel/openbabel/files/7521417/example_pngj.zip)

### PR DESCRIPTION
**Pull request by fredrikw**
This change should fix #2428 by checking for the PNG format header using an `unsigned char`. Also added a regression test that tries to read SMILES data encoded in a png file.

### CODE REVIEW

**Comment by ghutchis** [comment]
What changed so much with the `tests/CMakeLists.txt` file?

**Comment by fredrikw** [comment]
No idea, seems to be some whitespace/line ending issue. Will fix shortly.

**Comment by e-kwsm** [comment]
> What changed so much with the `tests/CMakeLists.txt` file?

Line ending seems to be changed from LF to CRLF.

**Comment by fredrikw** [comment]
No the line endings are corrected. But it still has merge conflicts, will see if I can fix those...

**Comment by fredrikw** [comment]
That should fix the merge conflicts as well...

**Comment by ghutchis** [comment]
Failures are unrelated - I'll merge this, thanks.

**Pull request merged**
