### PR TITLE
Add stereo + obfunctions + kekulize to ruby binding

### PR DESCRIPTION
**Pull request by CamAnNguyen**
Add ruby bindings for functions of `kekulize.h` , `obfunctions.h` and related header

### CODE REVIEW

**Comment by baoilleach** [comment]
Looks fine, but we should really fix OBChemTsfm.Init and indeed any API function that takes a reference to a std::string (or even just takes a std::string).

**Comment by CamAnNguyen** [comment]
I have removed the `OBChemTsfm.Init` part, SWIG works with `std::string` without define the type map

**Comment by ghutchis** [comment]
@baoilleach - I think for now, I'm fine with merging as-is. Agreed?

**Comment by baoilleach** [comment]
Yes.

**Pull request merged**
