### PR TITLE
Mol2 reader does not like the extra blank lines

### PR DESCRIPTION
**Pull request by mwojcikowski**
Additional extra lines look, make Mol2 reader stop after first molecule. Just get rid of them.

### CODE REVIEW

**Comment by baoilleach** [comment]
Is it a problem with the reader or the writer?

**Comment by mwojcikowski** [comment]
Apparently I was a bit hasty with that fix, therefore it should be
rejected. Although I have problem with some gzipped files, where only first
molecule is read. If you gunzipped them they work flawlessly. But as I
mentioned, I blamed it on extra spaces. Did you have such a problem with
gzipped files?

----
Pozdrawiam,  |  Best regards,
Maciek Wójcikowski
maciek@wojcikowski.pl

2015-04-20 23:00 GMT+02:00 baoilleach <notifications@github.com>:

**Comment by baoilleach** [comment]
(I have had problems with gzipped SDF files on Windows in particular.)

**Comment by mwojcikowski** [comment]
Nope, Debian Sid x64 here. And that was .mol2.gz

2015-04-21 12:11 GMT+02:00, baoilleach <notifications@github.com>:
> (I have had problems with gzipped SDF files on Windows in particular.)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/openbabel/openbabel/pull/144#issuecomment-94729941


-- 
----
Pozdrawiam,  |  Best regards,
Maciek Wójcikowski
maciek@wojcikowski.pl

**Pull request closed without merging**
