### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by ghutchis**
Add a code of conduct - generally hasn't been a problem, but better to be up-front.

### CODE REVIEW

**Comment by baoilleach** [comment]
Sure. I note though that it's not going to be confidential if sent to openbabel-devel@lists.sf.net, but the text gives that impression.

**Comment by ghutchis** [comment]
Good point. I was thinking more along the lines of someone saying "hey, I have an issue" but I'd welcome either:
a) a way to provide confidentiality (since we don't have a separate maintainers list)
b) re-wording for the text

Not sure of either, although I can take a stab at rewording.

**Comment by baoilleach** [comment]
Just make it clear that it's not confidential, but that they can email the lead developer confidentially if they want. I don't think you need to provide an email address - they'll figure it out.

**Comment by baoilleach** [comment]
Where does this appear, BTW?

**Comment by ghutchis** [comment]
It doesn't automatically appear anywhere. Here's an example for atom:

https://github.com/atom/atom
(it's linked from the README)
https://github.com/atom/atom/community

**Pull request merged**
