### PR TITLE
Minor speedup to avoid repeated calls to IsOption by caching some options

### PR DESCRIPTION
**Pull request by baoilleach**
In the SMILES writer, the profiler showed IsOption() as talking up a percent or two. I've cached a few of the options in the functions highlighted by the profiler. Is it possible to persist some variables between repeated calls to the writer (or would this cause some threading issues) as this would be a potential improvement?

### CODE REVIEW

**Comment by ghutchis** [comment]
It would depend on how the variables are retained, as far as threading goes.

**Comment by baoilleach** [comment]
Just reran the timings. Locally, based on master + AvoidSSSR, IsOption takes 3.8%. With this change, it's 2.0%, with 0.6% from BuildCanonTree, 0.3% from WriteMolecule, and 0.3% from CreateCansmiString.

One thing to think about is whether we could speed up IsOption itself, e.g. think about what sort of std::map we use, or whether to use a map at all for single letter boolean options.

If you have no issues, I think for the moment that I'm happy with this PR as it is, and leave the more complicated issue of retaining state for another day.

**Comment by baoilleach** [comment]
Actually - maybe there's one or two more options that could be cached. Could you leave this here for the moment, and I might push another commit later this week...

**Comment by baoilleach** [comment]
Ok - ready to go. Down to 1.3%.

**Pull request merged**
