### PR TITLE
Patch "fromfile" method for partialcharge

### PR DESCRIPTION
**Pull request by mj-harvey**
See associated issue
https://github.com/openbabel/openbabel/issues/157

### CODE REVIEW

**Comment by baoilleach** [comment]
2d3c0c1 looks like it contains things it shouldn't.

**Comment by mj-harvey** [comment]
Huh, don't know what went wrong there; I'll have another go in a tick (Can you tell I'm new to git?)

**Comment by ghutchis** [comment]
I think I'd really prefer to see a clean patch. I'm going to close this and rebase myself.

**Comment by ghutchis** [comment]
I opened up #167 but I'm seeing issues with tests (MMFF94 and Gasteiger). Can you take a look? I don't have time tonight to see what's happening.

**Pull request closed without merging**
