### PR TITLE
add Molecule.make2D function

### PR DESCRIPTION
**Pull request by eloyfelix**
I wanted to generate molfile with 2d coordinates from SMILES and I was not able to do it in a nice way using pybel.

The only option I had was doing something like this:

from pybel import _operations
_operations['gen2D'].Do(mol.OBMol)

I think that would be nicer to have a mol.make2D() function.

### CODE REVIEW

**Comment by baoilleach** [comment]
You could have used mol.draw(show=False, update=True).

**Comment by eloyfelix** [comment]
yep, true, but when I tried it before writing this tiny piece of code I had the no coords warning:

import pybel
mol_smiles = pybel.readstring('smiles', "CCCN")
mol_smiles.draw(show=False, update=True)
ob_molfile = mol_smiles.write('mol')


==============================
*** Open Babel Warning  in WriteMolecule
  No 2D or 3D coordinates exist. Stereochemical information will be stored using an Open Babel extension. To generate 2D or 3D coordinates instead use --gen2D or --gen3D.

now I can see that despite the warning the coordinates are set. this is a bit confusing

**Comment by baoilleach** [comment]
That *is* confusing. I'll look into it. Would you still think make2d is needed if this is fixed?

**Comment by eloyfelix** [comment]
In my opinion it looks much clearer .make2D() than .draw(show=False, update=True). 
It should be more efficient(I didn't time it) as there is much more code and checks in the draw function.
So I would add it :)

**Comment by baoilleach** [comment]
Fair enough. Could you remove the comment in the docstring though, as OASA is not used for 2D coordinate generation. (It was once.)

**Comment by eloyfelix** [comment]
done!

**Comment by baoilleach** [comment]
...and done!

**Pull request merged**
