### PR TITLE
G09test

### PR DESCRIPTION
**Pull request by dspoel**
This is to test OB:s capacity to generate correct bond orders by comparing reading a correct SDF file to a Gaussian log file. More tests can be added later.

### CODE REVIEW

**Comment by dspoel** [comment]
Testing this PR will fail until the OB code is fixed to deal with charges during bond order assignment.

**Comment by dkoes** [comment]
If you make the sulfur trioxide bond pattern a bit more specific (specifying hybridization) that fixes the issue:
```
--- a/data/bondtyp.txt
+++ b/data/bondtyp.txt
@@ -47,7 +47,7 @@
 # Sulfite
 [#16D3]([#8D1])([#8D1-])([#8D1-])              0 1 2 0 2 1 0 3 1
 # Sulfur trioxide
-[#16D3]([#8D1])([#8D1])([#8D1])                        0 1 2 0 2 2 0 3 2
+[#16D3^2]([#8D1])([#8D1])([#8D1])                      0 1 2 0 2 2 0 3 2
 # Sulfites
 [#16D3]([#8D1])([#8])([#8])                    0 1 2 0 2 1 0 3 1
 # Disulfur monoxide
```

I would also change `import openbabel as ob` to `from openbabel import openbabel as ob` in `testgauss.py` and would consider adding AssignTotalChargeToAtoms to the Gaussian reader (it seems reasonable for the atomic formal charge to add up to the molecular):
```
--- a/src/formats/gaussformat.cpp
+++ b/src/formats/gaussformat.cpp
@@ -1391,6 +1391,7 @@ namespace OpenBabel
       dp->SetOrigin(fileformatInput);
       mol.SetData(dp);
     }
+    mol.AssignTotalChargeToAtoms(total_charge);
     mol.SetTotalCharge(total_charge);
     mol.SetTotalSpinMultiplicity(spin_multiplicity);
 
```

**Comment by dspoel** [comment]
Thanks for the suggestions, the bondtyp.txt fix seems to work. The import change in python did not work.

**Comment by dkoes** [comment]
That's concerning since that is the correct way to import openbabel in openbabel3 (even though it seems redundant).  I would be worried you might have multiple versions of openbabel in your path and aren't importing the right one.

**Comment by dspoel** [comment]
Hm, I cleaned some stuff and now have one OB installation left. Still

build/test % python ../../openbabel/test/testgauss.py
OpenBabel not found, stopping test.
build/test % echo $PYTHONPATH
/Users/spoel/Alexandria/AlexandriaDB/PYTHON:/Users/spoel/Liquids/PYTHON:/Users/spoel/GG/openbabel-alexandria/install/lib/python3.8/site-packages/openbabel
build/test % ls /Users/spoel/GG/openbabel-alexandria/install/lib/python3.8/site-packages/openbabel
__init__.py	__pycache__/	_openbabel.so*	openbabel.py	pybel.py

**Comment by ghutchis** [comment]
I'm going to squash, merge, and fix the Python test.

**Pull request merged**
