### PR TITLE
Switch to rapidjson library for JSON parsing/writing

### PR DESCRIPTION
**Pull request by mcs07**
- Use rapidjson instead of json-cpp.
- Better method for including the JSON library: Instead of including the full source in the Open Babel repository, CMake looks for rapidjson on the system. If it doesn't find it, it downloads the latest version on demand and uses that. This is also a possible model for how the InChI code could work.
- Better detection of supported native CPU optimizations at compile time (used by rapidjson).
- Convert the existing PubChem and ChemDoodle JSON formats to use rapidjson.
- Fix a few minor bugs and add proper tests for the existing JSON formats.

Should hopefully be faster:

```
(jsoncpp) $ python -m timeit -n 1000 -v 'import pybel;list(pybel.readfile("pcjson","CID_6857552_2D.json"))'
raw times: 2.15 1.45 1.45
1000 loops, best of 3: 1.45 msec per loop
```

```
(rapidjson) $ python -m timeit -n 1000 -v 'import pybel;list(pybel.readfile("pcjson","CID_6857552_2D.json"))'
raw times: 1.55 0.818 0.818
1000 loops, best of 3: 818 usec per loop
```

### CODE REVIEW

**Comment by baoilleach** [comment]
If you think this is the way to go, then go for it. My token question is what happens if the user does not have internet access?

I see that rapidjson appears in Debian, though the version numbers are quite low. I'd be interested to hear what @mbanck thinks of this way of automatically downloading dependencies and whether there are steps we should take to help packagers.

**Comment by mbanck** [comment]
I think requiring either the library be installed on the system or an internet connection is reasonable, e.g. Psi4 is doing the `external/` thing quite extensively.

I have asked the Debian rapidjson maintainer about his plans for 1.1.0, it is currently only in experimental.

Finally, I am more worried about the vectorization, is that going to be optional or easy to disable? Just because you build on a machine with SSEX.Y does not mean you run OpenBabel on one as well, and the machine you run it might have an older processor so you get SIGILL. If this is local to optionally building rapidjson, then it is not really an issue for packages, as they would use the already packaged rapidjson library, but I wanted to point this out.

**Comment by mcs07** [comment]
RDKit also does a similar thing with downloading to `external/`.

All the optimisation is off by default. You have to provide `-D OPTIMIZE_NATIVE=ON` to CMake to enable (an existing Open Babel option). I think it would actually be fine to have this on by default, seeing as it would be just as easy to disable.

rapidjson is header-only, so as far as I understand, whether or not it uses the extensions should be purely controlled by the Open Babel options.

**Comment by ghutchis** [comment]
@mcs07 We have generally defaulted to -DOPTIMIZE_NATIVE=OFF because it caused problems for far too many people (e.g., popcount).

As to needing an internet connection for building, Avogadro2 has moved to this system with CMake and it seems to work fine.

I haven't looked at the code, but certainly switching JSON parsing libraries is fine with me. I suspect we'll see more JSON formats soon (e.g., Chemical JSON.. a new quantum chemistry JSON format that's being finalized).

**Comment by mcs07** [comment]
Yeah, what prompted me to revisit this was talking with @greglandrum about new Chemical JSON formats - he has been exploring this in RDKit using rapidjson.

It generally looks like a more well-designed and well-maintained library compared to json-cpp. There are also some additional features like json-schema and json-pointer support that will hopefully reduce the effort needed to add new formats in future.

**Comment by greglandrum** [comment]
I haven't really looked at alternatives, but I find rapidjson to be quite nice. It's well documented, header-only, and pretty easy to use.

**Pull request merged**
