### PR TITLE
pyttest_babel test passes on clean build

### LINKED ISSUE #2662: pytest_babel test fails on clean build
## Environment Information

Open Babel version: 
[latest master commit](https://github.com/openbabel/openbabel/tree/32cf131444c1555c749b356dab44fb9fe275271f)

Operating system and version:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

## Expected Behavior

All tests should pass on a clean build

## Actual Behavior

pytest_babel fails

## Steps to Reproduce

Build a clean project
```sh
   mkdir build
   cd build
   cmake ..
   make -j2
```
## Suspected Problem

Looks like the issue is a obrms is missing on line 54 in [tools/CMakeLists.txt](https://github.com/openbabel/openbabel/blob/32cf131444c1555c749b356dab44fb9fe275271f/tools/CMakeLists.txt#L54)

When I add obrms to that line all my tests pass.

## Errors from failing tests

```sh
Test project /home/jfkonecn/repos/openbabel/build
    Start 212: pytest_babel
1/1 Test #212: pytest_babel .....................***Failed  Error regular expression found in output. Regex=[ERROR]  1.16 sec
/home/jfkonecn/repos/openbabel/scripts/python:/home/jfkonecn/repos/openbabel/build/lib
.......E/usr/lib/python3.10/subprocess.py:955: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdin = io.open(p2cwrite, 'wb', bufsize)
/usr/lib/python3.10/subprocess.py:961: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.10/subprocess.py:966: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
........
======================================================================
ERROR: testOBRMS (__main__.TestOBabel)
Sanity checks for obrms
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jfkonecn/repos/openbabel/test/testbabel.py", line 529, in testOBRMS
    output, err = run_exec( "obrms -t 10 %s %s"%(sdffile,sdffile))
  File "/home/jfkonecn/repos/openbabel/test/testbabel.py", line 56, in run_exec
    p = Popen([exe] + broken[1:],
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '../bin/obrms'

----------------------------------------------------------------------
Ran 16 tests in 1.128s

FAILED (errors=1)

CMake Error at pytest_babel.cmake:20 (MESSAGE):
  1




0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.16 sec

The following tests FAILED:
        212 - pytest_babel (Failed)
Errors while running CTest
```

### PR DESCRIPTION
**Pull request by jfkonecn**
fixes #2662

### CODE REVIEW

**Comment by baoilleach** [comment]
What's going on with Line 56 where obrms is added if Eigen3 is present? Can you work out whether this dependency is true?

**Comment by dkoes** [comment]
It is - need the matrix math.

**Comment by baoilleach** [comment]
Then I'm very confused.

**Comment by dkoes** [comment]
I have a distinct memory of trying to remove this dependency from the cmake file and it not working, but I've just tried it and it seems fine - obrms uses the built-in matrix3x3 rather than an eigen matrix so it isn't obvious to me why the current code needs the EIGEN dependency.

**Pull request closed without merging**
