### PR TITLE
Improve tools/obconformer.cpp

### PR DESCRIPTION
**Pull request by e-kwsm**
* Enable to accept forcefield (default: MMFF94)
* remove unused variables
* clang-format

### CODE REVIEW

**Comment by e-kwsm** [comment]
At present it is impossible to change the forcefield from MMFF94, so we cannot perform obconformer on some systems, e.g., borane.

In this PR I simply add forcefield as the last argument—use it if passed, otherwise defaulted to MMFF94.

**Comment by ghutchis** [comment]
I don't use this tool directly, or i would have noticed the issue. Adding an option is a good choice, but the default should be:
- use MMFF94 if possible
- if not, use UFF

if the user actually asks for a specific forcefield, then try it or fail

If you're willing to make that small change, i'll happily accept the patch, thanks.

**Comment by e-kwsm** [comment]
> Adding an option is a good choice, but the default should be:
> - use MMFF94 if possible
> - if not, use UFF
>
> if the user actually asks for a specific forcefield, then try it or fail

Implemented.

**Comment by ghutchis** [comment]
Thanks - definitely improved 😄

**Pull request merged**
