### PR TITLE
Improve performance of element handling

### PR DESCRIPTION
**Pull request by baoilleach**
As described over at https://github.com/openbabel/enhancement-proposals/pull/4.

Briefly, the old element handling code had some performance problems. I have written a faster replacement. It has the following additional benefits:
1. No need for a global etab or isotab and associated initialization.
2. The elements are now available as consts (e.g. OBElements::Carbon) to replace functions such as IsCarbon().
3. No need for text/header files in data dir.

Timing comparison: get the symbol for elements 1 to 100 and convert back to atomic number (repeat x10000). 0.82s old vs 0.02s new. A more realistic conversion is to just do carbon: 0.14s old vs 0.01s new.

```
void test_OBElements()
{
  clock_t start = clock();
  unsigned int tot = 0;
  for (unsigned int N = 0; N < 10000; ++N) {
    for (unsigned int i = 1; i < 100; ++i) {
      const char *elem = OBElements::GetSymbol(6);
      unsigned int atomic_num = OBElements::GetAtomicNum(elem);
      tot += atomic_num;
    }
  }
  clock_t stop = clock();
  double sum = (double)(stop - start) / CLOCKS_PER_SEC;
  printf("%.2f s\n", sum);
  
  OBElementTable etab;
  start = clock();
  tot = 0;
  for (unsigned int N = 0; N < 10000; ++N) {
    for (unsigned int i = 1; i < 100; ++i) {
      const char *elem = etab.GetSymbol(6);
      unsigned int atomic_num = etab.GetAtomicNum(elem);
      tot += atomic_num;
    }
  }
  stop = clock();
  sum = (double)(stop - start) / CLOCKS_PER_SEC;
  printf("%.2f s\n", sum);
}
```

### CODE REVIEW

**Comment by baoilleach** [comment]
Updated timings, for the record, with 3 signif figures and 10x more iterations:

Timing comparison: get the symbol for elements 1 to 100 and convert back to atomic number (repeat x100000). 8.05s old vs 0.187s new. A more realistic conversion is to just do carbon: 1.34s old vs 0.078s new.

**Comment by baoilleach** [comment]
Good to merge? Or not...?

**Comment by ghutchis** [comment]
Yep, it looks good. Sorry for the delay

**Comment by n-yoshikawa** [comment]
Could you show me how to use `OBElements` in Python binding?
For example, how can I replace the following code?
```python
import openbabel

etab = openbabel.OBElementTable()
print(etab.GetSymbol(6))
```

**Comment by baoilleach** [comment]
https://open-babel.readthedocs.io/en/latest/UseTheLibrary/migration.html#handling-of-elements-and-related-information

**Comment by n-yoshikawa** [comment]
I tried the following `test.py` in the current master,
```
from openbabel import openbabel
  
print(openbabel.OBElements.GetSymbol(6))
```
but it yielded the followng error.
```
$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    print(openbabel.OBElements.GetSymbol(6))
AttributeError: module 'openbabel.openbabel' has no attribute 'OBElements'
```

**Comment by baoilleach** [comment]
Just GetSymbol will work without the OBElements.

**Pull request merged**
