### PR TITLE
Switch to C++11 nullptr using modernize-use-nullptr

### PR DESCRIPTION
**Pull request by ghutchis**
Hopefully solves #2206

### CODE REVIEW

**Comment by yurivict** [comment]
This patch still leaves a lot of ```NULL``` symbols, in the code, and some errors are still present:
```
/usr/ports/science/openbabel/work/openbabel-openbabel-3-1-0/src/math/spacegroup.cpp:360:39: error: reinterpret_cast from 'nullptr_t' to 'OpenBabel::transform3d *' is not allowed
    return (i == m_transforms.end())? reinterpret_cast<transform3d*>(NULL): *i++;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/science/openbabel/work/openbabel-openbabel-3-1-0/src/math/align.cpp:448:14: error: C-style cast from 'nullptr_t' to 'double' is not allowed
      return (double) NULL;
             ^~~~~~~~~~~~~
```

**Comment by e-kwsm** [comment]
In #2044 I performed [`clang-tidy --fix --checks=-*,modernize-use-nullptr`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html).

**Comment by yurivict** [comment]
This command wasn't comprehensive enough.

**Comment by ghutchis** [comment]
@e-kwsm - yes, I remember thinking "oh, we definitely want to do more clang-tidy after the next release"

**Comment by ghutchis** [comment]
I'm dropping this in favor of #2044.

**Pull request closed without merging**
