### PR TITLE
Changed indexing of fragments, should fix #1889

### LINKED ISSUE #1889: 2D depict generates weird result for fragmented SMILES
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: both master/2.4.90 and 2.4.1
Operating system and version: Ubuntu on windows

## Expected Behavior

image

## Steps to Reproduce

$ obabel test.smi -Otest.png

test.smi:
[H+].CC[O-].CC[O-]

I uploaded more examples here. I was trying to find a general rule about when the bug would show up but couldn't find one. It seems super random. 
[pics.zip](https://github.com/openbabel/openbabel/files/2385189/pics.zip)

### PR DESCRIPTION
**Pull request by fredrikw**
This should fix #1889 
It looks like there was a problem with 0-based and 1-based indexing in mcdlutil.

### CODE REVIEW

**Comment by baoilleach** [comment]
Is it possible to add a test case? E.g. a test for a weirdly long bond. Would be great. Details at https://open-babel.readthedocs.io/en/latest/Contributing/Testing.html but feel free to ask me any questions.

**Comment by fredrikw** [comment]
Yeah, I know ther are no tests, I did this on my Windows machine at work and I'm not in complete agreement with the build system... I'll try to add a test shortly, a simple one is to run gen2D on [H+].CC[O-].CC[O-] and make sure that all atoms have unique x- and y-positions (that is the real problem, the long bonds are just a symptom). Before the change I get the molfile (notice the coordinates for the last three atoms):
    
    OpenBabel09241813522D
    
      7  4  0  0  0  0  0  0  0  0999 V2000
        0.8210   -0.3437    0.0000 H   0  3  0  0  0  0  0  0  0  0  0  0
        9.9282   -1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        8.1962   -2.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        6.4641   -1.0000    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
        6.4641   -6.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        6.4641   -6.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        6.4641   -6.0000    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
      2  3  1  0  0  0  0
      3  4  1  0  0  0  0
      5  6  1  0  0  0  0
      6  7  1  0  0  0  0
    M  CHG  3   1   1   4  -1   7  -1
    M  END

After the change I got:

```
 OpenBabel09241813522D

  7  4  0  0  0  0  0  0  0  0999 V2000
    3.2321   -3.0000    0.0000 H   0  3  0  0  0  0  0  0  0  0  0  0
    4.9641   -0.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.0981   -1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.2321   -0.5000    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
    2.2321   -1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3660   -0.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5000   -1.0000    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
  2  3  1  0  0  0  0
  3  4  1  0  0  0  0
  5  6  1  0  0  0  0
  6  7  1  0  0  0  0
M  CHG  3   1   1   4  -1   7  -1
M  END
```

**Comment by fredrikw** [comment]
So testing for very short bond lengths should do it...

**Comment by baoilleach** [comment]
Gotcha. I'll tell you what - with this info, I'll put together the test
with the testfiles from the original bug report.

- Noel

**Comment by fredrikw** [comment]
Great! Thanks!

**Comment by fredrikw** [comment]
I found a Linux system that I could set up for testing, so I added a test. It's a Python test that relies on itertools.combinations, is that ok?

**Comment by baoilleach** [comment]
Very high tech. I'm a two-loop man myself. :-) Thanks for sorting this out - as you can see, it takes a while for me to do anything.

**Pull request merged**
