### PR TITLE
Improve distance geometry coordinate generation methods.

### PR DESCRIPTION
**Pull request by ghutchis**
Use partial metrization and damped stereochemical corrections.

This is still incomplete - causes some test failures.

### CODE REVIEW

**Comment by arkose** [comment]
It looks like this commit may have broken compilation:

[ 19%] Building CXX object src/CMakeFiles/plugin_ops.dir/ops/gen3d.o
.../openbabel/src/ops/gen3d.cpp: In member function ‘virtual bool OpenBabel::OpGen3D::Do(OpenBabel::OBBase*, const char*, OpenBabel::OBOp::OpMap*, OpenBabel::OBConversion*)’:
.../openbabel/src/ops/gen3d.cpp:90:3: error: ‘OBDistanceGeometry’ was not declared in this scope
   OBDistanceGeometry dg;
   ^
.../openbabel/src/ops/gen3d.cpp:98:5: error: ‘dg’ was not declared in this scope
     dg.Setup(*pmol, attemptBuild); // use the bond lengths and angles if we ran the builder
     ^
make[3]: *** [src/CMakeFiles/plugin_ops.dir/ops/gen3d.o] Error 1
make[3]: Leaving directory `.../openbabel/build'
make[2]: *** [src/CMakeFiles/plugin_ops.dir/all] Error 2
make[2]: Leaving directory `.../openbabel/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `.../openbabel/build'
make: *** [openbabel/build/bin/babel] Error 2

**Comment by ghutchis** [comment]
That's very strange, since it builds on both Travis and Appveyor.

Can you do a "make clean; make" ?

**Comment by arkose** [comment]
Of course. Here are the Makefile instructions used:

- - - - -
all: openbabel/build/bin/babel

openbabel:
        git clone git://github.com/openbabel/openbabel.git
openbabel/build: openbabel
        cd openbabel && git pull && mkdir build
openbabel/build/Makefile: openbabel/build
        cd openbabel && cd build && cmake -DBUILD_GUI=OFF -DBUILD_DOCS=OFF -DENABLE_TESTS=OFF ..
openbabel/build/bin/babel: openbabel/build/Makefile
        cd openbabel/build && make
- - - - -

Here's what eventually happens happens when I run `make` (... replaces unnecessary path details):

- - - - -
[ 22%] Building CXX object src/CMakeFiles/plugin_ops.dir/ops/gen3d.o
.../openbabel/src/ops/gen3d.cpp: In member function ‘virtual bool OpenBabel::OpGen3D::Do(OpenBabel::OBBase*, const char*, OpenBabel::OBOp::OpMap*, OpenBabel::OBConversion*)’:
.../openbabel/src/ops/gen3d.cpp:90:3: error: ‘OBDistanceGeometry’ was not declared in this scope
   OBDistanceGeometry dg;
   ^
.../openbabel/src/ops/gen3d.cpp:98:5: error: ‘dg’ was not declared in this scope
     dg.Setup(*pmol, attemptBuild); // use the bond lengths and angles if we ran
     ^
make[3]: *** [src/CMakeFiles/plugin_ops.dir/ops/gen3d.o] Error 1
make[3]: Leaving directory `.../openbabel/build'
make[2]: *** [src/CMakeFiles/plugin_ops.dir/all] Error 2
make[2]: Leaving directory `.../openbabel/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `.../openbabel/build'
make: *** [openbabel/build/bin/babel] Error 2
- - - - -

I then go into .../openbabel/build and run `make clean; make`, and it breaks at the same point:

- - - - -
[ 22%] Building CXX object src/CMakeFiles/plugin_ops.dir/ops/gen3d.o
.../openbabel/src/ops/gen3d.cpp: In member function ‘virtual bool OpenBabel::OpGen3D::Do(OpenBabel::OBBase*, const char*, OpenBabel::OBOp::OpMap*, OpenBabel::OBConversion*)’:
.../openbabel/src/ops/gen3d.cpp:90:3: error: ‘OBDistanceGeometry’ was not declared in this scope
   OBDistanceGeometry dg;
   ^
.../openbabel/src/ops/gen3d.cpp:98:5: error: ‘dg’ was not declared in this scope
     dg.Setup(*pmol, attemptBuild); // use the bond lengths and angles if we ran the builder
     ^
make[2]: *** [src/CMakeFiles/plugin_ops.dir/ops/gen3d.o] Error 1
make[1]: *** [src/CMakeFiles/plugin_ops.dir/all] Error 2
make: *** [all] Error 2
- - - - -

Very strange that it's building elsewhere, it doesn't seem like the kind of bug that would be system dependent.

I'm not sure if it will help, but I'll give some system information:

- - - - -
$ uname --operating-system --kernel-release --kernel-name
Linux 3.2.0-98-generic GNU/Linux
$ uname --kernel-version
#138-Ubuntu SMP Mon Jan 11 12:33:01 UTC 2016
$ uname --machine --processor --hardware-platform
x86_64 x86_64 x86_64
- - - - -

Here's my /proc/cpuinfo:

- - - - -
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Xeon(R) CPU E31245 @ 3.30GHz
stepping	: 7
microcode	: 0x23
cpu MHz		: 1600.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 6584.78
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Xeon(R) CPU E31245 @ 3.30GHz
stepping	: 7
microcode	: 0x23
cpu MHz		: 1600.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 6584.72
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Xeon(R) CPU E31245 @ 3.30GHz
stepping	: 7
microcode	: 0x23
cpu MHz		: 1600.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 6584.72
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Xeon(R) CPU E31245 @ 3.30GHz
stepping	: 7
microcode	: 0x23
cpu MHz		: 1600.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 6584.71
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 4
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Xeon(R) CPU E31245 @ 3.30GHz
stepping	: 7
microcode	: 0x23
cpu MHz		: 1600.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 6584.72
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 5
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Xeon(R) CPU E31245 @ 3.30GHz
stepping	: 7
microcode	: 0x23
cpu MHz		: 1600.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 6584.72
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 6
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Xeon(R) CPU E31245 @ 3.30GHz
stepping	: 7
microcode	: 0x23
cpu MHz		: 1600.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 5
initial apicid	: 5
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 6584.73
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Xeon(R) CPU E31245 @ 3.30GHz
stepping	: 7
microcode	: 0x23
cpu MHz		: 1600.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 6584.73
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
- - - - -

And here's my /proc/meminfo:

- - - - -
MemTotal:        8133496 kB
MemFree:         1332556 kB
Buffers:          198472 kB
Cached:          1463144 kB
SwapCached:            0 kB
Active:          5582092 kB
Inactive:         656896 kB
Active(anon):    4597284 kB
Inactive(anon):    36136 kB
Active(file):     984808 kB
Inactive(file):   620760 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:              1768 kB
Writeback:             0 kB
AnonPages:       4577472 kB
Mapped:           308328 kB
Shmem:             56048 kB
Slab:             219956 kB
SReclaimable:     151892 kB
SUnreclaim:        68064 kB
KernelStack:        7808 kB
PageTables:        63780 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     4066748 kB
Committed_AS:    9573052 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      134508 kB
VmallocChunk:   34359595004 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:     7632896 kB
DirectMap2M:      714752 kB
- - - - -

Let me know if any other sort of information might be helpful.

**Comment by baoilleach** [comment]
Is this resolved (i.e. the bug)? If not, what OS exactly and what compiler exactly?

**Pull request merged**
