### PR TITLE
Fix dg stereo

### PR DESCRIPTION
**Pull request by ghutchis**
Work in progress

### CODE REVIEW

**Comment by baoilleach** [comment]
While you're in there, it would be great if you could take a look at warnings in the file. There are a number of unused variables for example, as well as signed/unsigned comparisons. I'll paste mine in here, but your version is likely different (build with -DCMAKE_CXX_FLAGS="-W -Wall"):
```
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:489:68: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (nbr->GetIdx() == path[d] || nbr->GetIdx() == path[b])
                                                                    ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:503:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (nbr->GetIdx() == path[a] || nbr->GetIdx() == path[c])
                                        ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:503:68: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (nbr->GetIdx() == path[a] || nbr->GetIdx() == path[c])
                                                                    ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:509:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (nbr->GetIdx() == path[d] || nbr->GetIdx() == path[b])
                                        ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:509:68: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (nbr->GetIdx() == path[d] || nbr->GetIdx() == path[b])
                                                                    ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:389:18: warning: unused variable 'i' [-Wunused-variable]
     unsigned int i, j;
                  ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:389:21: warning: unused variable 'j' [-Wunused-variable]
     unsigned int i, j;
                     ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:429:19: warning: unused variable 'bond_id' [-Wunused-variable]
     OBStereo::Ref bond_id;
                   ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp: In member function 'OpenBabel::OBCisTransStereo* OpenBabel::OBDistanceGeometry::GetCisTransStereo(OpenBabel::OBBond*)':
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:587:19: warning: unused variable 'bond_id' [-Wunused-variable]
     OBStereo::Ref bond_id;
                   ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp: In member function 'void OpenBabel::OBDistanceGeometry::Set15Bounds()':
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:617:18: warning: unused variable 'i' [-Wunused-variable]
     unsigned int i, j;
                  ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:617:21: warning: unused variable 'j' [-Wunused-variable]
     unsigned int i, j;
                     ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp: In member function 'void OpenBabel::OBDistanceGeometry::TriangleSmooth(int)':
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:748:9: warning: unused variable 'loopCount' [-Wunused-variable]
     int loopCount = 0;
         ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp: At global scope:
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:745:8: warning: unused parameter 'iterations' [-Wunused-parameter]
   void OBDistanceGeometry::TriangleSmooth(int iterations)

/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp: In member function 'void OpenBabel::OBDistanceGeometry::AddConformer()':
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:1108:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (a->GetIdx() == origin || a->GetIdx() == second || a->GetIdx() == third)
                              ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:1108:55: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (a->GetIdx() == origin || a->GetIdx() == second || a->GetIdx() == third)
                                                       ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:1108:80: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (a->GetIdx() == origin || a->GetIdx() == second || a->GetIdx() == third)
                                                                                ^
/home/noel/Tools/openbabel-baoilleach/src/distgeom.cpp:1042:18: warning: unused variable 'attempts' [-Wunused-variable]
     unsigned int attempts = 0;

```

**Comment by ghutchis** [comment]
Yes, I haven't done much cleaning up or optimizing, because it's still working only ~75% of the time. Not bad, but not good either.

**Comment by ghutchis** [comment]
I think I finally understand the problem, but haven't had time to implement any possible solutions.

**Comment by ghutchis** [comment]
I'm closing this in favor of Naruki's #1875

**Pull request closed without merging**
